### ISSUE TITLE
'mediapipe' has no attribute 'solutions' in Python 3.14

### ISSUE THREAD

**Issue by ichlubna** [ck-zhang/EyeTrax#17]
Hi,
I have installed the package with `pip install eyetrax` but when running `eyetrax-demo --filter kalman`, I am getting:

```
 File "/home/ichlubna/.local/lib/python3.14/site-packages/eyetrax/app/demo.py", line 29, in run_demo
    gaze_estimator = GazeEstimator(model_name=args.model)
  File "/home/ichlubna/.local/lib/python3.14/site-packages/eyetrax/gaze.py", line 23, in __init__
    self.face_mesh = mp.solutions.face_mesh.FaceMesh(
                     ^^^^^^^^^^^^
AttributeError: module 'mediapipe' has no attribute 'solutions'
```

Seems like there were [changes](https://stackoverflow.com/questions/79857831/attributeerror-on-mediapipe-module) mediapipe. Will you consider updating the project for Python 3.14?

**Comment by couragetrain-stack** [comment]
@ichlubna  - It works with python 3.12, because mediapipe==0.10.21 
Beyond python 3.12, mediapipe starts using Tasks framework.

python 3.13 -> mediapipe ( 0.10.30 ) # Tasks framework - has no mediapipe.solutions
python 3.14 -> mediapipe ( 0.10.30 ) # Tasks framework - has no mediapipe.solutions

@ck-zhang I want to take the feature for migration of mediapipe from Solutions Framework to Tasks Framework.
I can deliver it by 29th Feb.

**Comment by CourageTrain** [comment]
https://github.com/ck-zhang/EyeTrax/pull/18/commits

It works - but, I need to read through docs more -
Tasks framework needs - a local face_landmarker.tasks - downloaded from https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker

Other than that, is compatibility to be maintained with older versions of mediapipe - how to navigate the constant mediapipe churn over the past 3 years?

**Comment by ck-zhang** [comment]
Hello, can you please report if this fixed in the latest version?

**Comment by ichlubna** [comment]
> Hello, can you please report if this fixed in the latest version?

Yes, fixed, thank you! One more little edit I had to make was:
```
help="Margin ratio for dense calibration (default 0.10 = 10%%)"
```
